os:
- linux
language:
- python
python:
- 3.8.5
install:
- pip install -r flaskProject/requirements.txt
- ./create_db.sh
script:
- echo "Success"
branches:
  only:
  - master
  - develop
  - us6_deployment
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: lBuz4FCMFfrsQLMCyWXQ3kbOtZlr3WC8KqNIwHAu4LjP228UbwJVrUdcwjWNl140G4vzoQd5uN4UsW73JOicNyfqZg5PFl4wAwrOvgs1JkwYTCDTcK53fgYeAVdRhVCudSvVax/65jYaCnpIf2unnsI1R/M8EAiqP3zqc40MXQrI0H51DDDphhCGM8OuSWMIov3B8Nts2xZY+EFtpYS0nKpLoIaEGts1KrxngW3XVVjLlHqTGfHXOjJ3RiN6aaxapqvjm3uOAumuNXvpPMTaHGwcO/XBrs2DJzF6gcPBJRhTuKNMfmlBEyR3S2ZVHDrFsKuighdoVMvMf1bsyP2ZSyQcY4T5/veHEsvb0xpByh2nO6CUI1WIBcdlY8e9ApLITpLgrIYp1WXW2DekWq0kYj0uV93oRfiWDv0741O+8aaNvOULu8XLy4u3C043Hxdw9L21UeDgIJndVPAI+3N6dfHyDjP9lxb5XcOzLSoUftLExxLJA9vkhA9BTEM1uNVoF74XkQyYyUEw+wCxrSdMmpY31Z6bxf5GJFRsyHEMCm5r8N3Qtxt/6Yvk3eZlWhwSXi8p3evB8+C7FC7MZisuIPbA0yrddXoIaWa5PiMoghGO5DPO/yKk/X9I8XxdoNasCjSF2FoB/6xyAnzS5w4YKYobt9s5Q1Bqk3rjauzmieU=
  app:
    master: mooving
    develop: mooving-develop
    us6_deployment: provant999
