os:
  - linux
language:
  - node_js
node_js:
  - 15.0.1
install:
  - npm install -g @vue/cli
before_script:
  - export FRONTEND=mooving
  - ./create_frontend.sh
script:
  - ./build_frontend.sh
  - npm run test:unit
after_success:
  - ./move_frontend.sh
branches:
  only:
  - main
  - develop
  - TR8T1_CTVue
before_deploy:
  - cd flaskProject
  - heroku 
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: cEQKjP0/iwu1w0pejwgucUD4oRHDBErb3iQbYPlV6ARxDcQFa/d6FfBu/UkhwqH09msfVnEwmF0XRgU54C3fPl3v4oZrT/vHnRm/yihXaqkm8PWBdStFC8WPTIX9KJjpx6eol4G3dLl0joNjN5eq3OfH3hjfpHzjfOZls12sVJ5LdjfaXoFpv5vI4o00GD84yP3Ttlnhs31R6hbNodc2LliqjRjHHka0NMGm/7ZPBtb+BHCzePly0r7VRf+8VstqbaPZSktBHMkm9wYhXrTd0u/4BdFvlNk40guWoGKjdJb0AW12IRiRoOdKel+m0YBEABHu9TF3fAz+la32SBsisPeyHA5IRpxdtn/OkheInQ7EFZ08RhmvSqRGnt52+Qd+IqXJu3005lYWanxdy0YOP07XbD2LejfdbvQnV98ukT6jEvNJrzWFHFMYUw5yYxnXLKRqAT/LkKdmspNnHEnUlNwx3NG47BpKRh6DNDK6fQmFef6p24ogwDMJOUkuRToZu7YDBn9jjg3WcsinxYA+HNYQEb60oh5dDrkFdyBlW9Yil3KXVR0KN6kzzxKAYBmcWmE9Gflo0j7OXfsz0CzDGnu07kipuVu2L1KR78VLc3n7WoES3JoAS0Q1DvFfMW/3h/Pl8Czjb2pU9n6K2/x0Wr0AHOv9ZMDCHbKL0gKGgEo=
  app:
    main: mooving
    develop: mooving-develop
    TR8T1_CTVue: provant999
  run: ./server_create_db.sh
