os:
- linux
language:
- python
node_js:
- 15.0.1
python:
- 3.8.6
before_install:
- nvm install node --reinstall-packages-from=node
install:
- npm install -g @vue/cli
before_script:
- export FRONTEND=mooving
- "./create_frontend.sh"
script:
- "./test_frontend.sh"
- "./test_backend.sh"
- "./build_frontend.sh"
after_success:
- "./move_frontend.sh"
branches:
  only:
  - main
  - develop
  - TR8T2_CTFlask
before_deploy:
- cd flaskProject
- heroku
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Qh+SbDhP9/cQCpxrEEDauZc1EQDs7AUbNNn5qGdEIAtqzj4yRzAva20wcskertexwckMwpjMDs8cRsbJuTjGqvWTgO+PxkTYZbTU+r5BLrkXyKoD68Cw8tMe+oFkWQYzqF4p0fLWZQIY85SbDeG8YIxOXT7ymvgbPPTqfSzuE+HVCip85vxW//HCKPMToYjwFcDQFyq9JSk7K+xjeCeXhLzfNa1Wa4tAGnqa0cldyKzaamXQI3WDVGq6GlHIudOZbdOo/BBwbFNXqH7vB9ijzR33Yhp6CiwqjSkGByPeBOtmt5CYoLx9e4bgNRgxq81RM6iWuZ8MqcVH8ERN1FyKfMNRzxxsTin6DSHwE9ykFE7uXAi0PkyZXNrj7MDd4Zi0nyp/oxZ63rD4AlE2G0V5TFZq6HS4nZXmyxJjAlt5YtEw4MgmwK2jpl+HiRa89IOvLtVxNXwVudvKNKJL3KnKxor/A4kRGi77nEpHQNb/wzS/l03mCe0XrxHaHVGf53Pb1USbijriiZwdpSY2Q4jPADeRtzX3vNgWTP/BrvpBBh03jbkNKtXvdiSPVMzp1VbO34OuI70dVCk09mvaJk7ky8DBk4vD+M5X0xETM5B6NMoKb2a3+/+angKMxZKmxAsUYMpG9Gcb0jNzl7VqEjV07Kjx+1qpTV7B3TxBJiG2Gyo=
  app:
    main: mooving
    develop: mooving-develop
    TR8T2_CTFlask: provant999
  run: "./server_create_db.sh"
